### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by imspikey** [icflorescu/openshift-cartridge-mysql#4]
Hello when I execute this command:
 ${OPENSHIFT_DATA_DIR}.mysql/bin/mysql --socket=${TMP}mysql.sock -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'secret' WITH GRANT OPTION; FLUSH PRIVILEGES;"

I get: "bash: /var/lib/openshift/5886fa347628e14f050000b9/app-root/data/.mysql/bin/mysql: No such file or directory"

I searched for .mysql directory but couldn't find it? is there an error in the installation process ?!

**Comment by imspikey** [comment]
Ok I found the solution after reading the installation code.

looks like I have exceed my quota  so the installation cant be complete :(

**Comment by icflorescu** [comment]
So, is this still an issue?

**Comment by imspikey** [comment]
Since this is an issue related to  storage capacity, the only solution is to increase my storage capacity which I might consider doing later.

Thank you for this great cartridge 👍
